### ISSUE TITLE
Simple code does not work

### ISSUE THREAD

**Issue by cactusmonkey** [Diaoul/arduino-Maxbotix#1]
Not sure whats going on here, but this is the error that I get when trying to verify the Simple code:

MaxbotixSonar/Maxbotix.cpp.o: In function `Maxbotix::getRange()':
/usr/share/arduino/libraries/MaxbotixSonar/Maxbotix.cpp:77: undefined reference to `operator new[](unsigned int)'
/usr/share/arduino/libraries/MaxbotixSonar/Maxbotix.cpp:67: undefined reference to `operator delete[](void*)'
collect2: ld returned 1 exit status

Any help would be greatly appreciated!

**Comment by Diaoul** [comment]
Never been able to reproduce.
