### ISSUE TITLE
Disabled RxSoftwareSerial not reflected in examples

### ISSUE THREAD

**Issue by Leenix** [Diaoul/arduino-Maxbotix#4]
rangeSensorTx features in both Simple and Advanced examples, but has been disabled in the library files. 

You can either remove rangeSensorTX from the examples, or restore RxSoftwareSerial as it has been disabled for a reason not known to me.

**Comment by Diaoul** [comment]
This is to avoid conflict with existing libraries. If needed you can rename it and use it.

**Comment by Perraudeau** [comment]
It's possible to add this lines in example files around to TX parts (declaration and utilisation): 

* `#ifdef MAXBOTIX_WITH_SOFTWARE_SERIAL`
* `#endif `

**Comment by Diaoul** [comment]
Can you submit a PR with that?
