### ISSUE TITLE
Multi-instance software serial

### ISSUE THREAD

**Issue by JRicardoPC** [Diaoul/arduino-Maxbotix#6]
Hi,

I have a problem when use this library, i use two maxbotix in arduino nano, and when i read from Serial, using Rx SoftwareSerial.h, i don't receive anything from Monitor Serie.

But if i use one maxbotix with serial, and another with Digital, the program work without any problem. 
This is my code:
#include "Maxbotix.h"
#include <ros.h>
#include <ros/time.h>
#include <sensor_msgs/Range.h>

//Sonar A (EZ4)
//#ifdef MAXBOTIX_WITH_SOFTWARE_SERIAL
	Maxbotix rangeSensorTXA(6, Maxbotix::TX, Maxbotix::LV);
//#endif
//Set up the ros node and publisher
sensor_msgs::Range sonar_TXA_msg;
ros::Publisher pub_sonar_TXA("sonarTXA", &sonar_TXA_msg);

//sonar B (EZ0)
//#ifdef MAXBOTIX_WITH_SOFTWARE_SERIAL
	Maxbotix rangeSensorTXB(8, Maxbotix::TX, Maxbotix::LV);
//#endif
//Set up the ros node and publisher
sensor_msgs::Range sonar_TXB_msg;
ros::Publisher pub_sonar_TXB("sonarTXB", &sonar_TXB_msg);

ros::NodeHandle nh;

void setup()
{
   Serial.begin(9600);
   //seleccionamos los pin de control
   //Sonar A
   pinMode(5, OUTPUT);

   //Sonar B
   pinMode(4, OUTPUT);
   
   nh.initNode();

   //mensaje SERIAL A
   nh.advertise(pub_sonar_TXA);
   sonar_TXA_msg.radiation_type = sensor_msgs::Range::ULTRASOUND;
   sonar_TXA_msg.header.frame_id = "/sonar_range";
   sonar_TXA_msg.field_of_view = 0.4;
   sonar_TXA_msg.min_range = 0.15;
   sonar_TXA_msg.max_range = 6.45;

   //mensaje SERIAL B
   nh.advertise(pub_sonar_TXB);
   sonar_TXB_msg.radiation_type = sensor_msgs::Range::ULTRASOUND;
   sonar_TXB_msg.header.frame_id = "/sonar_range";
   sonar_TXB_msg.field_of_view = 0.7;
   sonar_TXB_msg.min_range = 0.15;
   sonar_TXB_msg.max_range = 6.45;
}

long range_timer;

void loop()
{
   if ((millis() - range_timer) > 1000)
   {
       //SERIAL A
      digitalWrite(5, HIGH);
      delayMicroseconds(50);
      digitalWrite(5, LOW);
      sonar_TXA_msg.range = rangeSensorTXA.getRange();
      sonar_TXA_msg.header.stamp = nh.now();
      Serial.print("TXA = ");
      Serial.println(sonar_TXA_msg.range);
      pub_sonar_TXA.publish(&sonar_TXA_msg);

      //SERIAL B
      digitalWrite(4, HIGH);
      delayMicroseconds(50);
      digitalWrite(4, LOW);
      sonar_TXB_msg.range = rangeSensorTXB.getRange();
      sonar_TXB_msg.header.stamp = nh.now();
      Serial.print("TXB = ");
      Serial.println(sonar_TXB_msg.range);
      pub_sonar_TXB.publish(&sonar_TXB_msg);

      Serial.println(" ");
      range_timer = millis();
   }
   nh.spinOnce();
}

Thanks so much and sorry for my english.
Skained

**Comment by Diaoul** [comment]
This may have something to do with [the limitations of SoftwareSerial](https://www.arduino.cc/en/Reference/SoftwareSerial), have you checked if this applies to you?

I would advise to only use one SoftwareSerial and the other as HardwareSerial.

**Comment by JRicardoPC** [comment]
Hi,
I solved my problem. I had a problem with the pin control, i change this and now works. 
Thanks and sorry for the issues
Skained
